name: Hello-world
on:
  push: 
    branches: main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: echo "Hello World!!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good-bye-world
        run: echo "Good bye world"
        shell: bash
