name: hello-world
on: push
      branches:
        - main
      pull_request:
          - main
      workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: my-step
         run: echo "Hello-World!!"
         shell: bash 

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye_world
        run: echo "Goodbye World"
        shell: bash
